# -*- coding: utf-8 -*-
"""Adult Income Dataset.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qp2qqrFcLkwM3it9tLU_6rjit13WPaMC
"""

import pandas as pd
import numpy as np
import re
import nltk
import spacy
import seaborn as sns
import matplotlib.pyplot as plt

from google.colab import files
uploaded = files.upload()

df = pd.read_csv("adult.csv")

df.head() #View first 5 rows

df.shape

df.info() #Check structure

df.columns

df.describe() #Check statistics

df.isnull().sum() #Fix Missing Data

df['income'].value_counts()

df.drop_duplicates(inplace=True)#  Remove duplicates

df.dropna(inplace=True)  # Remove missing values

print("Missing Values:")

print("\n")

print(df.isnull().sum())

""" **VISUALIZE CATEGORY DISTRIBUTION**"""

plt.figure(figsize=(15,6))

sns.countplot(x=df['income'])

plt.xticks(rotation=90)

plt.title("Income Distribution")

plt.xlabel("Income")

plt.ylabel("Count")

plt.show()

"""**Gender Distribution**"""

plt.figure(figsize=(6,4))
sns.countplot(data=df, x='income')
plt.title("Income Distribution")
plt.show()

"""**Age Distribution**"""

plt.figure(figsize=(8,5))
sns.histplot(df['age'], bins=30, kde=True)
plt.title("Age Distribution")
plt.xlabel("Age")
plt.show()

"""**Education Level Distribution**"""

plt.figure(figsize=(12,6))
sns.countplot(
    data=df,
    y='education',
    order=df['education'].value_counts().index
)
plt.title("Education Distribution")
plt.show()

"""**Workclass Distribution**"""

plt.figure(figsize=(10,5))
sns.countplot(
    data=df,
    y='workclass',
    order=df['workclass'].value_counts().index
)
plt.title("Workclass Distribution")
plt.show()

"""**Income vs Gender**"""

plt.figure(figsize=(6,4))
sns.countplot(data=df, x='income', hue='gender')
plt.title("Income by Gender")
plt.show()

"""**Income vs Education**"""

plt.figure(figsize=(12,6))
sns.countplot(
    data=df,
    y='education',
    hue='income',
    order=df['education'].value_counts().index
)
plt.title("Income by Education")
plt.show()

"""**Hours Worked Per Week**"""

plt.figure(figsize=(8,5))
sns.histplot(df['hours-per-week'], bins=30, kde=True)
plt.title("Hours Worked Per Week")
plt.show()

"""**Correlation Heatmap**"""

numeric_df = df.select_dtypes(include=np.number)

plt.figure(figsize=(10,6))
sns.heatmap(
    numeric_df.corr(),
    annot=True,
    cmap='coolwarm',
    fmt='.2f'
)
plt.title("Correlation Heatmap")
plt.show()

"""**HEATMAP OF CATEGORY COUNTS**"""

category_counts = df['workclass'].value_counts().reset_index()

category_counts.columns = ['Category', 'Count']

pivot_data = category_counts.pivot_table(
    values='Count',
    index='Category'
)

plt.figure(figsize=(8,10))

sns.heatmap(
    pivot_data,
    annot=True,
    cmap='viridis'
)

plt.title("Workclass Frequency Heatmap")

plt.show()

"""**Age vs Hours Worked**"""

plt.figure(figsize=(8,5))
sns.scatterplot(
    data=df.sample(3000, random_state=42),
    x='age',
    y='hours-per-week',
    alpha=0.6
)
plt.title("Age vs Hours Worked")
plt.show()

"""**Income Percentage Pie Chart**"""

plt.figure(figsize=(10,10))

df['income'].value_counts().plot.pie(
    autopct='%1.1f%%',
    startangle=90
)

plt.title("Income Distribution")

plt.ylabel('')

plt.show()

""" **TOP 20 MOST COMMON WORDS**"""

from collections import Counter

all_words = " ".join(df['workclass']).split()

word_freq = Counter(all_words)

common_words = word_freq.most_common(20)

words = [word[0] for word in common_words]
counts = [word[1] for word in common_words]

plt.figure(figsize=(14,6))

sns.barplot(x=counts, y=words)

plt.title("Top 20 Most Common Words")

plt.xlabel("Frequency")

plt.ylabel("Words")

plt.show()

"""**Top 10 Countries**"""

plt.figure(figsize=(10,5))
df['native-country'].value_counts().head(10).plot(kind='bar')
plt.title("Top 10 Countries")
plt.ylabel("Count")
plt.show()

"""**Boxplot of Age by Income**"""

plt.figure(figsize=(8,5))
sns.boxplot(data=df, x='income', y='age')
plt.title("Age Distribution by Income")
plt.show()

"""**Capital Gain Distribution**"""

plt.figure(figsize=(8,5))
sns.histplot(df['capital-gain'], bins=50)
plt.title('Capital Gain Distribution')
plt.show()

"""**Pairplot**"""

sample_df = df.sample(1000, random_state=42)

sns.pairplot(
    sample_df,
    vars=['age','educational-num','hours-per-week'],
    hue='income'
)
plt.show()

"""**CONFUSION MATRIX**"""

from sklearn.model_selection import train_test_split

X = df.drop('income', axis=1)
y = df['income']

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline

# Import models and metrics
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import MultinomialNB
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier
from sklearn.metrics import accuracy_score, confusion_matrix

# Identify categorical and numerical columns
categorical_features = X.select_dtypes(include='object').columns
numerical_features = X.select_dtypes(include=['int64', 'float64']).columns

# Create a column transformer for one-hot encoding categorical features
# and passing numerical features through
preprocessor = ColumnTransformer(
    transformers=[
        ('num', 'passthrough', numerical_features),
        ('cat', OneHotEncoder(handle_unknown='ignore'), categorical_features)
    ])

# Apply the preprocessing to X_train and X_test
X_train_processed = preprocessor.fit_transform(X_train)
X_test_processed = preprocessor.transform(X_test)

print("Data preprocessing (One-Hot Encoding) complete.")
print(f"Shape of processed X_train: {X_train_processed.shape}")
print(f"Shape of processed X_test: {X_test_processed.shape}")

"""**Word cloud**"""

from wordcloud import WordCloud

text = " ".join(df['occupation'])

wordcloud = WordCloud(
    width=1000,
    height=500,
    background_color='black'
).generate(text)

plt.figure(figsize=(15,7))

plt.imshow(wordcloud)

plt.axis('off')

plt.show()

from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer(
    max_features=5000,
    ngram_range=(1,2)
)

X_tfidf = tfidf.fit_transform(df['occupation'])

# y = df['encoded_category'] # 'encoded_category' is not defined. If intended for use, please create this column first.

lr_model = LogisticRegression(max_iter=1000)

lr_model.fit(X_train_processed, y_train)

lr_preds = lr_model.predict(X_test_processed)

print("LOGISTIC REGRESSION ACCURACY")
print(accuracy_score(y_test, lr_preds))

nb_model = MultinomialNB()

nb_model.fit(X_train_processed, y_train)

nb_preds = nb_model.predict(X_test_processed)

print("NAIVE BAYES ACCURACY")
print(accuracy_score(y_test, nb_preds))

rf_model = RandomForestClassifier()

rf_model.fit(X_train_processed, y_train)

rf_preds = rf_model.predict(X_test_processed)

print("RANDOM FOREST ACCURACY")
print(accuracy_score(y_test, rf_preds))

from xgboost import XGBClassifier # Explicitly import XGBClassifier here
from sklearn.preprocessing import LabelEncoder # Import LabelEncoder

xgb_model = XGBClassifier()

# Encode y_train and y_test to numerical values for XGBoost
le = LabelEncoder()
y_train_encoded = le.fit_transform(y_train)
y_test_encoded = le.transform(y_test)

xgb_model.fit(X_train_processed, y_train_encoded)

xgb_preds = xgb_model.predict(X_test_processed)

print("XGBOOST ACCURACY")
print(accuracy_score(y_test_encoded, xgb_preds)) # Use encoded y_test for accuracy

from sklearn.metrics import confusion_matrix # Explicitly import confusion_matrix here

cm = confusion_matrix(y_test, xgb_preds)

plt.figure(figsize=(14,12))

sns.heatmap(
    cm,
    annot=True,
    fmt='d',
    cmap='Blues'
)

plt.title("Confusion Matrix")

plt.xlabel("Predicted")

plt.ylabel("Actual")

plt.show()